name: Build and test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.25
      with:
          required-ros-distributions: foxy

    - name: Update rosdep
      run: rosdep update

    - name: Install missing dependencies
      run: DEBIAN_FRONTEND=noninteractive rosdep install --ignore-src --rosdistro foxy -y

    - name: Build
      run: colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: colcon test --event-handlers console_cohesion+
