name: Build and test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install missing dependencies
      run: rosdep update && DEBIAN_FRONTEND=noninteractive sudo rosdep install --from-paths . --ignore-src --rosdistro foxy -y

    - name: Build
      run: colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: colcon test --event-handlers console_cohesion+
