name: Build and test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.25
      with:
          required-ros-distributions: foxy

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.0.19
      with:
        target-ros2-distro: foxy
